const NOTIFICATION_TYPES = {
  CONTRACT_CREATED: "CONTRACT_CREATED",
  CONTRACT_ACTIVATED: "CONTRACT_ACTIVATED",
  CONTRACT_STAGE_ADVANCED: "CONTRACT_STAGE_ADVANCED",
  COMPLAINT_SUBMITTED: "COMPLAINT_SUBMITTED",
  COMPLAINT_REPLIED: "COMPLAINT_REPLIED",
  SUBSCRIPTION_RENEWAL_DUE: "SUBSCRIPTION_RENEWAL_DUE",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  SYSTEM_ERROR: "SYSTEM_ERROR",
};

const ENTITY_TYPES = {
  CONTRACT: "CONTRACT",
  COMPLAINT: "COMPLAINT",
  SUBSCRIPTION: "SUBSCRIPTION",
  SYSTEM: "SYSTEM",
};

module.exports = { NOTIFICATION_TYPES, ENTITY_TYPES };
