const NOTIFICATION_TYPES = {
  CONTRACT_CREATED: "CONTRACT_CREATED",
  CONTRACT_ACTIVATED: "CONTRACT_ACTIVATED",
  CONTRACT_STAGE_ADVANCED: "CONTRACT_STAGE_ADVANCED",
  COMPLAINT_SUBMITTED: "COMPLAINT_SUBMITTED",
  COMPLAINT_REPLIED: "COMPLAINT_REPLIED",
  SUBSCRIPTION_RENEWAL_DUE: "SUBSCRIPTION_RENEWAL_DUE",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  SYSTEM_ERROR: "SYSTEM_ERROR",
  // Financial Statements (FRD 2.3.14)
  STATEMENTS_GENERATED: "STATEMENTS_GENERATED",
  UNMAPPED_ACCOUNTS: "UNMAPPED_ACCOUNTS",
  TRIAL_BALANCE_OUT_OF_BALANCE: "TRIAL_BALANCE_OUT_OF_BALANCE",
  OPINION_DETERMINED: "OPINION_DETERMINED",
  REPORT_ISSUED: "REPORT_ISSUED",
};

const ENTITY_TYPES = {
  CONTRACT: "CONTRACT",
  COMPLAINT: "COMPLAINT",
  SUBSCRIPTION: "SUBSCRIPTION",
  SYSTEM: "SYSTEM",
  FINANCIAL_STATEMENTS: "FINANCIAL_STATEMENTS",
};

module.exports = { NOTIFICATION_TYPES, ENTITY_TYPES };
