module.exports = {
    // Branch Permissions
    CREATE_BRANCH: "CREATE_BRANCH",
    UPDATE_BRANCH: "UPDATE_BRANCH",
    VIEW_BRANCHES: "VIEW_BRANCHES",
    DELETE_BRANCH: "DELETE_BRANCH",
  
    // User Permissions
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    VIEW_USERS: "VIEW_USERS",
    DELETE_USER: "DELETE_USER",
  
    // Contract Permissions
    CREATE_CONTRACT: "CREATE_CONTRACT",
    REVIEW_CONTRACT: "REVIEW_CONTRACT",
    UPDATE_CONTRACT: "UPDATE_CONTRACT",
    ARCHIVE_CONTRACT: "ARCHIVE_CONTRACT",
    
    // Reports & Others
    VIEW_REPORTS: "VIEW_REPORTS",
    MANAGE_SETTINGS: "MANAGE_SETTINGS"
  };
  