const ROLES = {
  SUBSCRIBER_OWNER: "SUBSCRIBER_OWNER", // Admin of the subscriber
  BRANCH_MANAGER: "BRANCH_MANAGER",     // Implicit role for branch managers
  
  // Roles from Documentation
  SECRETARY: "SECRETARY",
  AUDIT_MANAGER: "AUDIT_MANAGER",
  TECHNICAL_AUDITOR: "TECHNICAL_AUDITOR",
  ASSISTANT_TECHNICAL_AUDITOR: "ASSISTANT_TECHNICAL_AUDITOR",
  FIELD_AUDITOR: "FIELD_AUDITOR",
  CONTACT_PERSON: "CONTACT_PERSON",
  QUALITY_CONTROL: "QUALITY_CONTROL",
  MANAGING_PARTNER: "MANAGING_PARTNER",
  REGULATORY_FILINGS_OFFICER: "REGULATORY_FILINGS_OFFICER",
  ARCHIVE: "ARCHIVE",
};

module.exports = { ROLES };
