const { ROLES } = require("./roles");
const PERMISSIONS = require("./permissions");

const ROLE_PERMISSIONS = {
  [ROLES.SUBSCRIBER_OWNER]: ["ALL_ACCESS"],
  
  [ROLES.SECRETARY]: [
    PERMISSIONS.CREATE_CONTRACT,
    PERMISSIONS.UPDATE_CONTRACT,
    PERMISSIONS.VIEW_BRANCHES,
    PERMISSIONS.VIEW_USERS,
  ],
  
  [ROLES.AUDIT_MANAGER]: [
    PERMISSIONS.REVIEW_CONTRACT,
    PERMISSIONS.VIEW_BRANCHES,
    PERMISSIONS.VIEW_USERS,
  ],
  
  [ROLES.BRANCH_MANAGER]: [
    PERMISSIONS.VIEW_BRANCHES,
    PERMISSIONS.UPDATE_BRANCH,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
  ]
};

module.exports = { ROLE_PERMISSIONS };