const PERMISSIONS = require('./permissions');

const ROLES = {
  SUBSCRIBER_OWNER: "SUBSCRIBER_OWNER", // Admin of the subscriber
  BRANCH_MANAGER: "BRANCH_MANAGER",     // Implicit role for branch managers
  
  // Roles from Documentation
  SECRETARY: "SECRETARY",
  AUDIT_MANAGER: "AUDIT_MANAGER",
  TECHNICAL_AUDITOR: "TECHNICAL_AUDITOR",
  ASSISTANT_TECHNICAL_AUDITOR: "ASSISTANT_TECHNICAL_AUDITOR",
  FIELD_AUDITOR: "FIELD_AUDITOR",
  CONTACT_PERSON: "CONTACT_PERSON",
  QUALITY_CONTROL: "QUALITY_CONTROL",
  MANAGING_PARTNER: "MANAGING_PARTNER",
  REGULATORY_FILINGS_OFFICER: "REGULATORY_FILINGS_OFFICER",
  ARCHIVE: "ARCHIVE",
};

// Default permissions for each role
const ROLE_PERMISSIONS = {
  [ROLES.SECRETARY]: [
    PERMISSIONS.CREATE_CONTRACT,
    PERMISSIONS.UPDATE_CONTRACT,
    PERMISSIONS.VIEW_BRANCHES,
    PERMISSIONS.VIEW_USERS,
  ],
  [ROLES.AUDIT_MANAGER]: [
    PERMISSIONS.REVIEW_CONTRACT,
    PERMISSIONS.VIEW_BRANCHES,
    PERMISSIONS.VIEW_USERS,
  ],
  [ROLES.BRANCH_MANAGER]: [
    PERMISSIONS.VIEW_BRANCHES,
    PERMISSIONS.UPDATE_BRANCH,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER
  ]
  // ... You can add more defaults here later
};

module.exports = {
  ROLES,
  ROLE_PERMISSIONS
};
